// Liste des pays avec indicatifs internationaux et drapeaux emoji
export type Country = {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  dial: string; // sans le +
  flag: string; // emoji
};

export const COUNTRIES: Country[] = [
  { code: "FR", name: "France", dial: "33", flag: "🇫🇷" },
  { code: "BE", name: "Belgique", dial: "32", flag: "🇧🇪" },
  { code: "CH", name: "Suisse", dial: "41", flag: "🇨🇭" },
  { code: "LU", name: "Luxembourg", dial: "352", flag: "🇱🇺" },
  { code: "MC", name: "Monaco", dial: "377", flag: "🇲🇨" },
  { code: "CA", name: "Canada", dial: "1", flag: "🇨🇦" },
  { code: "US", name: "États-Unis", dial: "1", flag: "🇺🇸" },
  { code: "GB", name: "Royaume-Uni", dial: "44", flag: "🇬🇧" },
  { code: "IE", name: "Irlande", dial: "353", flag: "🇮🇪" },
  { code: "DE", name: "Allemagne", dial: "49", flag: "🇩🇪" },
  { code: "AT", name: "Autriche", dial: "43", flag: "🇦🇹" },
  { code: "NL", name: "Pays-Bas", dial: "31", flag: "🇳🇱" },
  { code: "ES", name: "Espagne", dial: "34", flag: "🇪🇸" },
  { code: "PT", name: "Portugal", dial: "351", flag: "🇵🇹" },
  { code: "IT", name: "Italie", dial: "39", flag: "🇮🇹" },
  { code: "GR", name: "Grèce", dial: "30", flag: "🇬🇷" },
  { code: "DK", name: "Danemark", dial: "45", flag: "🇩🇰" },
  { code: "SE", name: "Suède", dial: "46", flag: "🇸🇪" },
  { code: "NO", name: "Norvège", dial: "47", flag: "🇳🇴" },
  { code: "FI", name: "Finlande", dial: "358", flag: "🇫🇮" },
  { code: "IS", name: "Islande", dial: "354", flag: "🇮🇸" },
  { code: "PL", name: "Pologne", dial: "48", flag: "🇵🇱" },
  { code: "CZ", name: "Tchéquie", dial: "420", flag: "🇨🇿" },
  { code: "SK", name: "Slovaquie", dial: "421", flag: "🇸🇰" },
  { code: "HU", name: "Hongrie", dial: "36", flag: "🇭🇺" },
  { code: "RO", name: "Roumanie", dial: "40", flag: "🇷🇴" },
  { code: "BG", name: "Bulgarie", dial: "359", flag: "🇧🇬" },
  { code: "HR", name: "Croatie", dial: "385", flag: "🇭🇷" },
  { code: "SI", name: "Slovénie", dial: "386", flag: "🇸🇮" },
  { code: "RS", name: "Serbie", dial: "381", flag: "🇷🇸" },
  { code: "UA", name: "Ukraine", dial: "380", flag: "🇺🇦" },
  { code: "RU", name: "Russie", dial: "7", flag: "🇷🇺" },
  { code: "TR", name: "Turquie", dial: "90", flag: "🇹🇷" },
  { code: "IL", name: "Israël", dial: "972", flag: "🇮🇱" },
  { code: "AE", name: "Émirats A. U.", dial: "971", flag: "🇦🇪" },
  { code: "SA", name: "Arabie Saoudite", dial: "966", flag: "🇸🇦" },
  { code: "QA", name: "Qatar", dial: "974", flag: "🇶🇦" },
  { code: "KW", name: "Koweït", dial: "965", flag: "🇰🇼" },
  { code: "BH", name: "Bahreïn", dial: "973", flag: "🇧🇭" },
  { code: "OM", name: "Oman", dial: "968", flag: "🇴🇲" },
  { code: "JO", name: "Jordanie", dial: "962", flag: "🇯🇴" },
  { code: "LB", name: "Liban", dial: "961", flag: "🇱🇧" },
  { code: "EG", name: "Égypte", dial: "20", flag: "🇪🇬" },
  { code: "MA", name: "Maroc", dial: "212", flag: "🇲🇦" },
  { code: "DZ", name: "Algérie", dial: "213", flag: "🇩🇿" },
  { code: "TN", name: "Tunisie", dial: "216", flag: "🇹🇳" },
  { code: "SN", name: "Sénégal", dial: "221", flag: "🇸🇳" },
  { code: "CI", name: "Côte d'Ivoire", dial: "225", flag: "🇨🇮" },
  { code: "CM", name: "Cameroun", dial: "237", flag: "🇨🇲" },
  { code: "ZA", name: "Afrique du Sud", dial: "27", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", dial: "234", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", dial: "254", flag: "🇰🇪" },
  { code: "IN", name: "Inde", dial: "91", flag: "🇮🇳" },
  { code: "PK", name: "Pakistan", dial: "92", flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh", dial: "880", flag: "🇧🇩" },
  { code: "LK", name: "Sri Lanka", dial: "94", flag: "🇱🇰" },
  { code: "CN", name: "Chine", dial: "86", flag: "🇨🇳" },
  { code: "JP", name: "Japon", dial: "81", flag: "🇯🇵" },
  { code: "KR", name: "Corée du Sud", dial: "82", flag: "🇰🇷" },
  { code: "HK", name: "Hong Kong", dial: "852", flag: "🇭🇰" },
  { code: "TW", name: "Taïwan", dial: "886", flag: "🇹🇼" },
  { code: "SG", name: "Singapour", dial: "65", flag: "🇸🇬" },
  { code: "MY", name: "Malaisie", dial: "60", flag: "🇲🇾" },
  { code: "TH", name: "Thaïlande", dial: "66", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", dial: "84", flag: "🇻🇳" },
  { code: "PH", name: "Philippines", dial: "63", flag: "🇵🇭" },
  { code: "ID", name: "Indonésie", dial: "62", flag: "🇮🇩" },
  { code: "AU", name: "Australie", dial: "61", flag: "🇦🇺" },
  { code: "NZ", name: "Nouvelle-Zélande", dial: "64", flag: "🇳🇿" },
  { code: "MX", name: "Mexique", dial: "52", flag: "🇲🇽" },
  { code: "BR", name: "Brésil", dial: "55", flag: "🇧🇷" },
  { code: "AR", name: "Argentine", dial: "54", flag: "🇦🇷" },
  { code: "CL", name: "Chili", dial: "56", flag: "🇨🇱" },
  { code: "CO", name: "Colombie", dial: "57", flag: "🇨🇴" },
  { code: "PE", name: "Pérou", dial: "51", flag: "🇵🇪" },
  { code: "VE", name: "Venezuela", dial: "58", flag: "🇻🇪" },
  { code: "UY", name: "Uruguay", dial: "598", flag: "🇺🇾" },
];

export const findCountryByCode = (code: string) =>
  COUNTRIES.find((c) => c.code === code) ?? COUNTRIES[0];